-- migrate:up

INSERT INTO settings (key, value, description) VALUES
	(
		'log_valve_requests',
		'true',
		'Write steam_api_requests / steam_gc_requests / replay_requests rows for each Valve attempt.'
	)
ON CONFLICT (key) DO NOTHING;

DO $$
DECLARE
	t text;
BEGIN
	FOREACH t IN ARRAY ARRAY[
		'steam_api_requests',
		'steam_gc_requests',
		'replay_requests'
	]
	LOOP
		EXECUTE format(
			$f$
			CREATE TABLE %I (
				id bigint GENERATED BY DEFAULT AS IDENTITY,
				created_at timestamptz NOT NULL DEFAULT now(),
				updated_at timestamptz NOT NULL DEFAULT now(),
				match_id bigint,
				method_name text NOT NULL,
				response_time double precision,
				response_status text,
				response_size_kb double precision,
				error_response text,
				PRIMARY KEY (id, created_at),
				CONSTRAINT %I CHECK (
					error_response IS NULL OR char_length(error_response) <= 1000
				)
			) PARTITION BY RANGE (created_at)
			$f$,
			t,
			t || '_error_len'
		);
		EXECUTE format(
			'CREATE INDEX %I ON %I (match_id)',
			t || '_match_id_idx',
			t
		);
		EXECUTE format(
			'CREATE INDEX %I ON %I (method_name, created_at DESC)',
			t || '_method_created_idx',
			t
		);
		EXECUTE format(
			'CREATE TRIGGER set_updated_at BEFORE UPDATE ON %I
			 FOR EACH ROW EXECUTE FUNCTION public.set_updated_at()',
			t
		);
	END LOOP;
END
$$;

CREATE OR REPLACE FUNCTION public.maintain_request_logs(
	retain_days integer DEFAULT 4
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
	tbl text;
	d date;
	start_day date;
	end_day date;
	part_name text;
	part_from timestamptz;
	part_to timestamptz;
	drop_name text;
BEGIN
	IF retain_days < 1 THEN
		RAISE EXCEPTION 'retain_days must be >= 1';
	END IF;
	start_day := (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::date - retain_days;
	end_day := (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::date + 2;
	FOREACH tbl IN ARRAY ARRAY[
		'steam_api_requests',
		'steam_gc_requests',
		'replay_requests'
	]
	LOOP
		d := start_day;
		WHILE d < end_day LOOP
			part_name := tbl || '_' || to_char(d, 'YYYY_MM_DD');
			part_from := (d::text || ' 00:00:00+00')::timestamptz;
			part_to := ((d + 1)::text || ' 00:00:00+00')::timestamptz;
			EXECUTE format(
				'CREATE TABLE IF NOT EXISTS %I PARTITION OF %I FOR VALUES FROM (%L) TO (%L)',
				part_name,
				tbl,
				part_from,
				part_to
			);
			d := d + 1;
		END LOOP;
		FOR drop_name IN
			SELECT c.relname
			FROM pg_inherits i
			JOIN pg_class c ON c.oid = i.inhrelid
			JOIN pg_class p ON p.oid = i.inhparent
			WHERE p.relname = tbl
				AND c.relkind = 'r'
				AND c.relname ~ ('^' || tbl || '_[0-9]{4}_[0-9]{2}_[0-9]{2}$')
				AND to_date(
					substring(c.relname FROM '[0-9]{4}_[0-9]{2}_[0-9]{2}$'),
					'YYYY_MM_DD'
				) < start_day
		LOOP
			EXECUTE format('DROP TABLE IF EXISTS %I', drop_name);
		END LOOP;
	END LOOP;
END;
$$;

SELECT public.maintain_request_logs();

-- migrate:down

DROP FUNCTION IF EXISTS public.maintain_request_logs(integer);

DROP TABLE IF EXISTS steam_api_requests;
DROP TABLE IF EXISTS steam_gc_requests;
DROP TABLE IF EXISTS replay_requests;

DELETE FROM settings WHERE key = 'log_valve_requests';
