import { describe, expect, test } from 'bun:test'
import { getAppSettings, replenishGap } from '#src/components/settings'

describe('replenishGap', () => {
	test('subtracts ready and pending from desired', () => {
		expect(replenishGap(10, 3, 2)).toBe(5)
		expect(replenishGap(3, 3, 0)).toBe(0)
		expect(replenishGap(3, 4, 0)).toBe(0)
	})
})

describe('getAppSettings', () => {
	test('reads seeded inventory and health settings', async () => {
		const settings = await getAppSettings()
		expect(settings.desiredApiKeys).toBe(3)
		expect(settings.desiredGcAccounts).toBe(10)
		expect(settings.proxyErrorThreshold).toBe(0.8)
		expect(settings.proxyErrorWindow).toBe(20)
		expect(settings.proxyRetestMax).toBe(20)
		expect(settings.gcAccountErrorThreshold).toBe(0.8)
		expect(settings.gcAccountErrorWindow).toBe(20)
		expect(settings.gcAccountRetestMax).toBe(20)
		expect(settings.apiKeyErrorThreshold).toBe(0.8)
		expect(settings.apiKeyErrorWindow).toBe(20)
		expect(settings.apiKeyRetestMax).toBe(20)
		expect(settings.livePollIntervalMs).toBe(3000)
		expect(settings.liveMissingThreshold).toBe(2)
		expect(settings.replayLiveDelayMs).toBe(30_000)
		expect(settings.historyPageSize).toBe(100)
		expect(settings.historyDetailsEnqueueLimit).toBe(5)
		expect(settings.historyReplayEnqueueLimit).toBe(50)
		expect(settings.seqBatchSize).toBe(100)
		expect(settings.steamApiMinIntervalMs).toBe(1000)
		expect(settings.historyNewestRefreshMs).toBe(3_600_000)
		expect(settings.historyExhaustedRefreshMs).toBe(86_400_000)
		expect(settings.replenishIntervalMs).toBe(60_000)
		expect(settings.retestIntervalMs).toBe(300_000)
		expect(settings.marketplaceBuyMax).toBe(10)
		expect(settings.marketplaceWaitMs).toBe(120_000)
		expect(settings.marketplaceMinIntervalMs).toBe(500)
		expect(settings.gcLogonAttempts).toBe(4)
		expect(settings.apiKeyRateLimitMs).toBe(60_000)
		expect(settings.gcAccountRateLimitMs).toBe(300_000)
		expect(settings.parserParallelism).toBe(10)
		expect(settings.historyFastPollMs).toBe(5000)
		expect(settings.historyFastPollLimit).toBe(100)
		expect(settings.historySlowPollMs).toBe(60_000)
		expect(settings.historySlowPollLimit).toBe(100)
	})
})
